name: Build and Deploy

on:
  push:
    tags:
      - v*
    branches:
      - main
      - site-deploy

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: SSH setup
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_DEPLOY_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        env:
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_DEPLOY_KEY: ${{secrets.SSH_DEPLOY_KEY}}
      - name: Rsync
        run: rsync -avz public/ deploy@developer.gosub.io:/wwwroot/gosub.io/public
